api_platform:
    title: Hello API Platform
    version: 1.0.0
    enable_entrypoint: true
    enable_docs: true
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 20
    collection:
        pagination:
            enabled: true
    serializer:
        hydra_prefix: true
